Lambda-School-Labs/sauti-databank-fe

- sauti/src/App.js
- sauti/src/Components/FilterBox.js
- sauti/src/Components/Graph.js
- sauti/src/Components/Queries.js
- sauti/src/Components/dataParse.js
added ability to single filter graph with colors, styling still needed
> committing working single filter with colored bars

- sauti/src/App.js
- sauti/src/Components/Graph.js
- sauti/src/Components/Queries.js
- sauti/src/Components/dataParse.js
- sauti/src/index.js
added deployed url to graphql config. React app now gets data from deployed backend.
> Form management

- sauti/src/App.js
- sauti/src/Components/Graph.js
- sauti/src/Components/Queries.js
- sauti/src/Components/dataParse.js
Built out getMostRequested function which counts and filters the request value when the indexBy is "request_type". Queries adjust dynamically according to index.
> Most requested graphs

- sauti/package.json
- sauti/src/Components/Queries.js
- sauti/src/Components/temp.css
- sauti/yarn.lock
implemented loading spinner animation for loading state
> added spinner and styling for loading state

- sauti/src/Components/dataParse.js
- sauti/yarn.lock
> Create filter form

- sauti/src/App.js
- sauti/src/Components/FilterBox.js
- sauti/src/Components/Queries.js
- sauti/src/Components/dataParse.js
Added dynamic argument functionality to queries file now accepting arguments from props.
> Dynamic arguments

- sauti/src/Components/dataParse.js
percentages now display properly on graphs which take in dynamic arguments
> committing working percentages on graphs which have dynamic arguments

- sauti/package.json
- sauti/src/App.test.js
- sauti/src/Components/Graph.js
- sauti/src/Components/dataParse.js
- sauti/src/Components/dataParse.spec.js
- sauti/yarn.lock
> committed tests for dataParse function

- sauti/package.json
- sauti/yarn.lock
removed jest causing conflicts with package
> removed jest because was causing issues building

- sauti/package.json
- sauti/src/App.js
- sauti/src/App.test.js
- sauti/src/Components/FilterBox.js
- sauti/yarn.lock
> Google analytics

- README.md
added contributors and technology additions to docs
> added contributors and technology additions to docs

- sauti/src/App.js
- sauti/src/App.scss
- sauti/src/Components/FilterBox.js
- sauti/src/Components/FilterBoxOptions.js
- sauti/src/index.css
> Filterbox update

- sauti/src/Components/Queries.js
Removed excessive console.log statements within Queries.js. No new functionality implemented.
> Removed excessive console.log statements in queries.js

- sauti/package-lock.json
- sauti/src/App.js
- sauti/src/Components/Queries.js
- sauti/src/Components/dataParse.js
Added comments to data parse file and renamed confusing variables
> Data parse comments

- sauti/src/App.js
- sauti/src/Components/FilterBox.js
- sauti/src/Components/dataParse.js
Updated the reset button so it returns all state back to it's initial values, current default graph view is single filtering view with the Most Requested Procedure Commodity graph.
> Reset button update

- sauti/src/Components/FilterBox.js
- sauti/src/Components/Queries.js
- sauti/src/Components/dataParse.js
> minor changes in dataParse.js

- sauti/src/App.js
- sauti/src/Components/AdditionalFilterOptions.js
- sauti/src/Components/FilterBox.js
- sauti/src/Components/Graph.js
- sauti/src/Components/Queries.js
- sauti/src/Components/dataParse.js
- sauti/src/DataParseHelpers/getIndex.js
Implemented an additional query to be ran if there's an additional filter selected, which will return a list of options for that additional filter value, which will be used to render the list of checkboxes in FilterBox.js
> Dynamic additional filter options

- sauti/src/Components/FilterBox.js
- sauti/src/Components/Queries.js
- sauti/src/Components/dataParse.js
Repushing. Original bug fix did not get pushed.
> Repushing to development

- sauti/src/App.js
- sauti/src/Components/FilterBox.js
- sauti/src/Components/Graph.js
- sauti/src/Components/Queries.js
- sauti/src/Components/dataParse.js
- sauti/src/index.js
The sample size is no longer broken. The dataStructure was being mutated in dataParse.js and was never fully being cleaned out when dataParse.js ran again.
> It is finished

- sauti/src/App.js
- sauti/src/Components/FilterBox.js
- sauti/src/Components/Graph.js
- sauti/src/Components/dataParse.js
Removed random console.log statements from within code, and uncommented any commented code that was removed during testing.
> Removed console.log statements and commented code

- sauti/src/Components/FilterBox.js
Added e.preventDefault to broken filterform.
> Added e.preventDefault to broken filterform.

- sauti/src/App.scss
- sauti/src/Components/Graph.js
> Csv dwnld undefined

- sauti/src/Components/Graph.js
- sauti/src/Components/dataParse.js
> fixed math.round for single filter error on ra and tza

- sauti/src/Components/Graph.js
git push origin csv-dwnld-undefined
> changed if statement to  heck for additionalFilter and not checkbox

- sauti/src/Components/Queries.js
- sauti/src/Components/dataParse.js
- sauti/src/Components/removeMultiple.js
> Remove requests data parse

- sauti/src/Components/FilterBox.js
> changed UX for filterbox buttons

- README.md
Updated readme to accommodate new changes to the React application
> updating readme to reflect most current additions including jest testing

- .env
- package.json
- src/Components/Queries.js
- src/dashboard/DashAbout.js
- src/dashboard/DashAccount.js
- src/dashboard/DashHome.js
- src/dashboard/DashLogin.js
- src/dashboard/DashLoginModal.js
- src/dashboard/DashLogout.js
- src/dashboard/DashNavBar.js
- src/dashboard/DashSignup.js
- src/dashboard/DashSignupModal.js
- src/dashboard/DashTools.js
- src/dashboard/Tools/EditModal.js
- src/dashboard/Tools/Gridoptions.js
- src/dashboard/Tools/Tools.js
- src/dashboard/auth/Auth.js
- src/dashboard/auth/ProtectedRoute.js
- src/dashboard/styledComponents/Index.js
- src/dashboard/styledComponents/LoginStyles.js
- src/dashboard/styledComponents/SignUpStyles.js
- src/dashboard/styledComponents/Styling.js
- src/index.js
- src/queries/mutation.js
- yarn.lock
> User dashboard

- .env
- .gitignore
> removed env file

- src/index.js
> add commment

- src/Components/FilterBox.js
- src/dashboard/CalendarModal.js
previously it was hard-coded to Jan 8 2020
I set the end date for the calendar to the current date.
> set calendar end date to today's date

- src/index.js
> changed tracking ID to sauti

- src/Components/Graph.js
- src/dashboard/DashNavBar.js
> Lukas jaronis

- src/Components/Graph.js
- src/dashboard/DashAccount.js
- src/dashboard/DashSignup.js
> trying to fix event

- public/index.html
- src/Components/FilterBox.js
> Social media

- src/Components/FilterBox.js
- src/dashboard/DashAccount.js
- src/index.js
> connect frontend to heroku

- src/App.scss
- src/Components/FilterBox.js
- src/Components/Graph.js
- src/GraphContainer.js
> Redesign of components that make up data page.

- src/dashboard/DashboardAccount/BiAnnuallyAccount.js
- src/dashboard/DashboardAccount/MonthlyAccount.js
- src/dashboard/DashboardAccount/NewSubscriberHandler.js
- src/dashboard/DashboardAccount/YearlyAccount.js
- src/index.js
> Paypal fix

- src/dashboard/DashboardAccount/useNewSubNameHook.js
- src/dashboard/LandingPageMap.js
- src/index.js
> updated .env

- src/Components/FilterBox.js
- src/Components/Graph.js
- src/GraphContainer.js
- src/dashboard/DashData.js
- src/dashboard/DashboardAccount/DashAccountUser.js
- src/dashboard/DownloadModal.js
> Data page cleanup

- src/Components/FilterBox.js
- src/GraphContainer.js
> Updates from meeting with Lance.

- src/App.scss
- src/Components/FilterBox.js
- src/Components/Graph.js
- src/GraphContainer.js
- src/dashboard/CalendarModal.js
- src/dashboard/DownloadModal.js
- src/hooks/useCalendar.js
> Cleanup download button and add more calendar options

- src/index.js
> push arbitrary change to debug env vars

- public/index.html
- src/Components/Graph.js
- src/dashboard/DashData.js
> Altering url

- public/index.html
- src/Components/Graph.js
- src/dashboard/DashData.js
> Updated urls

- src/Components/Graph.js
> Updated facebook share link

- src/Components/Graph.js
- src/dashboard/DashData.js
> Added a parsing case for the incoming facebook share url

- src/Components/Graph.js
> Fixed the download data set for subsamples

- src/App.scss
- src/index.css
> Adjusted widths to keep the page more stable

- src/App.scss
- src/index.css
> Reverted changes

- src/App.scss
- src/dashboard/DashData.js
- src/dashboard/DashboardAccount/DashAccountAdmin.js
- src/dashboard/DashboardAccount/DashAccountFree.js
- src/dashboard/DashboardAccount/EditAccount.js
- src/dashboard/Tools/EditModal.js
- src/dashboard/styledComponents/DashAccount.js
- src/index.js
- [ x ] Complete, tested, ready to review and merge
- [ x ] My code follows the style guidelines of this project
- [ x ] I have performed a self-review of my own code
- [ x ] My code has been reviewed by at least one peer
- [ x ] I have commented my code, particularly in hard-to-understand areas
- [ x ] There are no merge conflicts
> Account edit button

- .vscode/settings.json
- src/Components/CheckBox.js
- src/Components/LineGraph.js
- src/Components/LineGraphHelpers/scale100.js
- src/Components/LineGraphHelpers/topChecked.js
https://trello.com/c/3d6N7gHx
https://trello.com/c/efcLBONX
https://trello.com/c/lGRnjLQp
Line graph data to be normalized.
Dynamic display of checkbox options
Not able to see yearly displays
Line graph shows normalized data.
Top 7 lines display when click on data series search.
Only checkboxes will appear for categories with more than 10 sessions
Users can see yearly trends.
- [x ] New feature (non-breaking change which adds functionality
- [x ] Complete, but not tested (may need new tests).  Stakeholder wants to review it, prior to testing.
- [x ] I have commented my code, particularly in hard-to-understand areas
- [ x] …
> Line normal

- src/App.scss
- src/dashboard/DashboardAccount/BiAnnuallyAccount.js
- src/dashboard/DashboardAccount/MonthlyAccount.js
- src/dashboard/DashboardAccount/YearlyAccount.js
minor style tweaking to the monthly, bi-yearly, and yearly account pages
> monthly,bi-year,yearly style update

- src/Components/Footer.js
- src/Components/Graph.js
- src/GraphContainer.js
Full description of the process lives in this trello card: https://trello.com/c/lgD2jtG1
- [ x] New feature (non-breaking change which adds functionality)
- [ x] My code follows the style guidelines of this project
- [ x] I have performed a self-review of my own code
- [ x] I have commented my code, particularly in hard-to-understand areas
- [ x] I have made corresponding changes to the documentation
> Atomized footer

- src/Components/LineGraphButton.js
add text for Line Graph availability
- [x ] Complete, tested, ready to review and merge
- [x ] My code follows the style guidelines of this project
- [ x] I have performed a self-review of my own code
> LineGraphButton add text

- src/Components/LineGraph/LineGraph.js
Updated 3 functions in LineGraph.js, previously displayed data did not display last item
- [x ] Bug fix (non-breaking change which fixes an issue)
- [x ] My code has been reviewed by at least one peer
> LineGraph.js update functions updated, updatedYearly, updatedQtr

- src/Components/ChoroplethMap/AfricaMap.js
- src/Components/ChoroplethMap/ChoroplethParent.js
Added a variable dataView to enhance the initial zoom in feature of the Choropleth map.
- [ X] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x ] My code follows the style guidelines of this project
- [ x] There are no merge conflicts
> AfricaMap.js  add dataView variable for initial zoom 

- src/Components/ChoroplethMap/ChoroplethParent.js
> change name

- src/Components/LineGraph/DateSlider.js
- src/Components/LineGraph/LineGraph.js
- src/Components/LineGraph/LineRange.js
- src/Components/LineGraph/LineTime.js
Fixed Line graph, so that it will rerender even if the search is cached.
Line graph was not displaying if search was already stored in cache.
- [x ] Bug fix (non-breaking change which fixes an issue)
- [ x] My code follows the style guidelines of this project
- [x ] My code has been reviewed by at least one peer
- [x ] I have commented my code, particularly in hard-to-understand areas
- [ x] My changes generate no new warnings
- x[ ] There are no merge conflicts
> Line refresh

- src/Components/LineGraphButton.js
- src/Components/Queries2.js
Added display of filters choosen for Bar and Line Graph Searches
- [x ] New feature (non-breaking change which adds functionality)
- [x ] My code follows the style guidelines of this project
- [x ] My changes generate no new warnings
> Choosen filters

- src/Components/LineGraphButton.js
- src/Components/scss/lineGraphButton.scss
Styled buttons Bar, Line and Map buttons and Conditionally rendered
- [x ] My code follows the style guidelines of this project
- [ x] I have performed a self-review of my own code
- [ x] There are no merge conflicts
> User interface

- src/Components/ChoroplethMap/AfricaMap.js
- src/Components/ChoroplethMap/ChoroplethParent.js
- src/Components/ChoroplethMap/choroplethDataParse.js
- src/Components/ChoroplethMap/mapParcer.js
- src/Components/LineGraphButton.js
- src/Components/scss/lineGraph.scss
Connected filters Choropleth map.
- [x ] New feature (non-breaking change which adds functionality)
- [ x] My code follows the style guidelines of this project
- [x ] My code has been reviewed by at least one peer
- [x ] I have commented my code, particularly in hard-to-understand areas
- [ x] There are no merge conflicts
> Choropleth

- src/Components/LineGraphButton.js
Add Request Destination import to map
- [ x] New feature (non-breaking change which adds functionality)
- [ x] My code follows the style guidelines of this project
- [x ] My changes generate no new warnings
> add Requested Procedure to map
